// Code generated by qtc from "soaphlp.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line soaphlp.qtpl:1
package soaphlp

//line soaphlp.qtpl:2
import "encoding/xml"

//line soaphlp.qtpl:3
import "github.com/valyala/quicktemplate"

//line soaphlp.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line soaphlp.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line soaphlp.qtpl:6
func StreamEnvelope(qw422016 *qt422016.Writer, hdr, body interface{ StreamXML(*quicktemplate.Writer) }) {
//line soaphlp.qtpl:7
	qw422016.N().S(xml.Header)
//line soaphlp.qtpl:7
	qw422016.N().S(`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">`)
//line soaphlp.qtpl:9
	if hdr != nil {
//line soaphlp.qtpl:9
		qw422016.N().S(`<soapenv:Header>`)
//line soaphlp.qtpl:10
		hdr.StreamXML(qw422016)
//line soaphlp.qtpl:10
		qw422016.N().S(`</soapenv:Header>`)
//line soaphlp.qtpl:11
	}
//line soaphlp.qtpl:11
	qw422016.N().S(`<soapenv:Body>`)
//line soaphlp.qtpl:13
	body.StreamXML(qw422016)
//line soaphlp.qtpl:13
	qw422016.N().S(`</soapenv:Body></soapenv:Envelope>`)
//line soaphlp.qtpl:16
}

//line soaphlp.qtpl:16
func WriteEnvelope(qq422016 qtio422016.Writer, hdr, body interface{ StreamXML(*quicktemplate.Writer) }) {
//line soaphlp.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line soaphlp.qtpl:16
	StreamEnvelope(qw422016, hdr, body)
//line soaphlp.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line soaphlp.qtpl:16
}

//line soaphlp.qtpl:16
func Envelope(hdr, body interface{ StreamXML(*quicktemplate.Writer) }) string {
//line soaphlp.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line soaphlp.qtpl:16
	WriteEnvelope(qb422016, hdr, body)
//line soaphlp.qtpl:16
	qs422016 := string(qb422016.B)
//line soaphlp.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line soaphlp.qtpl:16
	return qs422016
//line soaphlp.qtpl:16
}
